#version 450

struct particleData
{
	vec4 position;
	vec4 veclocity;
	vec4 colour;	
};

layout(std430, binding = 0) buffer data
{
	particleData particles[];
};

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main()
{
	const float deltaTime = 0.1f;
	
	uint gid = gl_GlobalInvocationID.x;	
	
	vec3 p = particles[gid].position.xyz;
	vec3 v = particles[gid].veclocity.xyz;
	
	particles[gid].position.xyz += v * 0.1f;
	particles[gid].veclocity.xyz = v;
}